# See https://aka.ms/yaml
# This pipeline to be run on PRs

trigger:
  batch: true
  branches:
    include:
    - integration4
pr:
  branches:
    include:
    - integration4
  paths:
    exclude:
    - .gitignore
    - .readthedocs.yaml
    - contrib/pr_merge_check.py
    - contrib/check_qps.sh
    - docs/source
    - docs/CodeStyle.md
    - docs/LoggingStyle.md
    - docs/OptimizationStyle.md
    - README.md
    - NEWS
    - AUTHORS

extends:
  template: pr/main.yml
